version: '3.8'

services:
  # PostgreSQL
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
    depends_on:
      - zookeeper

  # Service Discovery
  eureka-server:
    image: openjdk:17-jdk-slim
    container_name: eureka-server
    ports:
      - "8761:8761"
    volumes:
      - ./eureka-server/target:/app
    command: java -jar /app/eureka-server.jar
    depends_on:
      - postgres
      - kafka

  #  Config Server
  config-server:
    image: openjdk:17-jdk-slim
    container_name: config-server
    ports:
      - "8888:8888"
    volumes:
      - ./config-server/target:/app
    command: java -jar /app/config-server.jar
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/AndreyF2018/config-repo.git  
      SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATHS: '{application}' 
      SPRING_CLOUD_CONFIG_SERVER_GIT_CLONE_ON_START: true  
      SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL: main
    depends_on:
      - eureka-server


  # User Service
  user-service:
    image: openjdk:17-jdk-slim
    container_name: user-service
    ports:
      - "8081:8081"
    volumes:
      - ./user-service/target:/app
    command: java -jar /app/user-service.jar
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - eureka-server
      - config-server
      - postgres
      - kafka

  # Notification Service
  notification-service:
    image: openjdk:17-jdk-slim
    container_name: notification-service
    ports:
      - "8082:8082"
    volumes:
      - ./notification-service/target:/app
    command: java -jar /app/notification-service.jar
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - eureka-server
      - config-server
      - kafka

  # API Gateway
  api-gateway:
    image: openjdk:17-jdk-slim
    container_name: api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./api-gateway/target:/app
    command: java -jar /app/api-gateway.jar
    depends_on:
      - eureka-server
      - config-server

volumes:
  postgres-data: